#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { parsePo } from '../compiler/po.ts'

const HELP = `
  i18n-compile - turn the PO catalogs into what the build consumes

  Reads messages/messages.pot (source texts) and messages/<locale>.po, and
  writes one catalog per locale. The output is a build artifact: edit the .po.

  Usage
    $ i18n-compile --locales en,zh [options]

  Options
    --locales <list>   comma separated, first one is the base locale
    --base <locale>    override the base locale
    --messages <dir>   catalog directory        (default: messages)
    --outdir <dir>     output directory         (default: same as --messages)
    --format <fmt>     json | js                (default: json)
    --skip-fuzzy       leave fuzzy translations out, falling back to the source
    -h, --help
`

function fail(message: string): never {
  process.stderr.write(`i18n-compile: ${message}\n`)
  process.exit(1)
}

const argv = process.argv.slice(2)
let locales: string[] = []
let baseOverride: string | undefined
let messagesDir = 'messages'
let outdir: string | undefined
let format = 'json'
let skipFuzzy = false

for (let index = 0; index < argv.length; index++) {
  const arg = argv[index]
  const next = (): string => {
    const value = argv[index + 1]
    if (value === undefined) fail(`${arg} needs a value`)
    index++
    return value
  }

  if (arg === '-h' || arg === '--help') {
    process.stdout.write(HELP)
    process.exit(0)
  } else if (arg === '--locales') locales = next().split(',')
  else if (arg === '--base') baseOverride = next()
  else if (arg === '--messages') messagesDir = next()
  else if (arg === '--outdir') outdir = next()
  else if (arg === '--format') format = next()
  else if (arg === '--skip-fuzzy') skipFuzzy = true
  else fail(`unknown option ${arg}`)
}

if (locales.length === 0) fail('--locales is required')
if (format !== 'json' && format !== 'js') fail(`unknown --format ${format}`)

const base = baseOverride ?? locales[0]!
const target = outdir ?? messagesDir
const out = (line: string) => process.stdout.write(`${line}\n`)

function read(file: string, locale: string) {
  try {
    return parsePo(readFileSync(file, 'utf8'), locale)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      fail(`${file} is missing - run i18n-extract first`)
    }
    throw error
  }
}

function write(locale: string, catalog: Record<string, string>): void {
  mkdirSync(target, { recursive: true })
  const sorted = Object.fromEntries(
    Object.keys(catalog)
      .sort()
      .map((key) => [key, catalog[key]!]),
  )

  const file = path.join(target, `${locale}.${format}`)
  const body =
    format === 'js'
      ? `// Generated by i18n-compile. Edit the .po file instead.\nexport default ${JSON.stringify(sorted, null, 2)}\n`
      : `${JSON.stringify(sorted, null, 2)}\n`

  writeFileSync(file, body)
  out(`  ${file}  (${Object.keys(sorted).length} message(s))`)
}

const template = read(path.join(messagesDir, 'messages.pot'), base)
const sources: Record<string, string> = {}
for (const entry of template.entries) {
  if (!entry.obsolete) sources[entry.id] = entry.source
}

write(base, sources)

for (const locale of locales.filter((item) => item !== base)) {
  const po = read(path.join(messagesDir, `${locale}.po`), locale)
  const catalog: Record<string, string> = {}
  let fuzzySkipped = 0

  for (const entry of po.entries) {
    if (entry.obsolete) continue
    if (!(entry.id in sources)) continue
    if (entry.target === '') continue
    if (entry.fuzzy && skipFuzzy) {
      fuzzySkipped++
      continue
    }
    catalog[entry.id] = entry.target
  }

  write(locale, catalog)
  if (fuzzySkipped > 0) out(`    ${fuzzySkipped} fuzzy entr(ies) skipped`)
}
